version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:latest
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: alakazan_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  spark:
    image: bitnami/spark:latest
    depends_on:
      - kafka
      - db
    environment:
      - SPARK_MODE=master
    ports:
      - "7077:7077"
      - "8080:8080"

  backend:
    build: ./backend
    depends_on:
      - kafka
      - db
      - spark
    environment:
      - POSTGRES_DB=alakazan_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    command: >
      sh -c "python manage.py migrate &&
            python ./backend/apps/ingestion/consumer.py & 
            gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"

volumes:
  postgres-data: